### ISSUE TITLE
Analysis Metadata in config.yaml?

### ISSUE THREAD

**Issue by ewallace** [riboviz/riboviz#166]
Thinking towards the examples repository, could we put relevant metadata in the config.yaml to indicate provenance of the yaml file?

Preliminary suggestion:

```
provenance:
  author: John Smith III
  email: John.Smith.III@ed.ac.uk
  date: 2020-04-01
  reference: Genome-Wide Analysis in Vivo of Translation with Nucleotide Resolution Using Ribosome Profiling, Ingolia et al 2009
  DOI: 10.1126/science.1168978
  notes: >
    Re-analysis of data from Ingolia 2009 to an updated yeast transcriptome.
```

**Comment by ewallace** [comment]
Request comments from @mikej888 and @FlicAnderson

**Comment by mikej888** [comment]
I think its a good idea. Users can add any additional content they wish to the YAML, RiboViz will ignore anything it does not use. Providing a schema for the provenance, with examples in YAML we write ourselves would be helpful for others.

**Comment by mikej888** [comment]
An update, to accommodate multiple authors, their website, and version TAG or COMMIT hash of the version of RiboViz they ran their script under.

```yaml
provenance:
  authors:
  - author: John Smith III
    email: John.Smith.III@ed.ac.uk
  - author: ...
    email: ...
  website: https://www.ed.ac.uk/some-bio-project
  date: 2020-04-01
  riboviz-version: TAG | COMMIT
  reference: Genome-Wide Analysis in Vivo of Translation with Nucleotide Resolution Using Ribosome Profiling, Ingolia et al 2009
  DOI: 10.1126/science.1168978
  notes: >
    Re-analysis of data from Ingolia 2009 to an updated yeast transcriptome.
```
