### ISSUE TITLE
Run on multiple input .fastq files per sample

### ISSUE THREAD

**Issue by ewallace** [riboviz/RiboViz#28]
Currently prepRiboviz.sh can take only one fastq.gz file for each sample, e.g. in the vignette_config.yaml:

```
fq_files: # fastq files to be processed
  WTnone: SRR1042855_s1mi.fastq.gz
  WT3AT: SRR1042864_s1mi.fastq.gz
```

However, sometimes the same sample is spread across multiple .fastq.gz files, for example if one sample is measured in multiple lanes of a sequencer or repeated in different runs. We should upgrade to account for this.

Maybe like this:

```
fq_files: # fastq files to be processed
  WTnone: SRR1042855_s1mi.fastq.gz SRR1042855_s2mi.fastq.gz
  WT3AT: SRR1042864_s1mi.fastq.gz
```

or like this:

```
fq_files: # fastq files to be processed
  WTnone: 
    fq1: SRR1042855_s1mi.fastq.gz 
    fq2: SRR1042855_s2mi.fastq.gz
  WT3AT: SRR1042864_s1mi.fastq.gz
```

Multiple input files could be particularly important when we address demultiplexing with inline barcodes, when it is very likely we will have several lanes of .fastq.gz for each multiplexed library.

**Comment by mikej888** [comment]
[Question: How To Merge Two Fastq.Gz Files?](https://www.biostars.org/p/81924/)

```console
$ cat file1.gz file2.gz file3.gz > allfiles.gz
```
gzip saves the name of the original file, if possible, and timestamp
```console
$ file allfiles.gz 
allfiles.gz: gzip compressed data, was "allfiles", last modified: Thu Nov 14 16:46:16 2019, from Unix
```

**Comment by mikej888** [comment]
From work on #84, proposed design...

For non-multiplexed data:

```yaml
fq_files:
  SampleX: .fastq.gz, .fastq.gz
  SampleY: .fastq.gz, .fastq.gz
  ...
```
```
FOREACH sample
  cat .fastq.gz fastq.gz ... > SampleX.fastq.gz
  ...execute cutadapt and following steps as at present...
```

For multiplexed data:

```yaml
multiplexed_files: .fastq.gz .fastq.gz ...
```
```
cat .fastq.gz .fastq.gz ... > multiplex.fastq.gz
...execute cutadapt and following steps as at present...
```

* Extend `create_fastq_files.py` to write out separate sample files which can be concatenated to yield the current ones.
* Write file concatenation function
* Add function add to `workflow.py`.
* Extend non-multiplexed file steps in`prep_riboviz.py`.
* Create new YAML configuration for testing.
* Extend multiplexed file steps in`prep_riboviz.py`.
* Create new YAML configuration for testing.
* Extend `test_prep_riboviz_simdata_umi.py`.
* Extend `test_prep_riboviz_simdata_multiplex.py`.
