### ISSUE TITLE
Check for None values when constructing R command-line invocations

### ISSUE THREAD

**Issue by mikej888** [riboviz/RiboViz#72]
Reported by @FlicAnderson in relation to #66.

If the YAML configuration file contains:

```yaml
features_file: data/yeast_features.tsv # file of features to correlate with ORFs
do_pos_sp_nt_freq: TRUE # Do calculate position-specific nucleotide freqeuency
t_rna: data/yeast_tRNAs.tsv # tRNA estimates
codon_pos: data/yeast_codon_pos_i200.RData # Codon positions in each gene
```
Running:
```console
$ python -m riboviz.tools.prep_riboviz --dry-run rscripts/ vignette/vignette_config.yaml
```
succeeds and prep_riboviz.sh contains:
```
Rscript --vanilla rscripts/generate_stats_figs.R --Ncores=1 --MinReadLen=10 
--MaxReadLen=50 --Buffer=250 --PrimaryID=Name --dataset=vignette 
--hdFile=vignette/output/WT3AT.h5 --out_prefix=vignette/output/WT3AT 
--orf_fasta=vignette/input/yeast_YAL_CDS_w_250utrs.fa --rpf=True 
--orf_gff_file=vignette/input/yeast_YAL_CDS_w_250utrs.gff3 
--dir_out=vignette/output --t_rna=data/yeast_tRNAs.tsv 
--codon_pos=data/yeast_codon_pos_i200.RData 
--features_file=data/yeast_features.tsv --do_pos_sp_nt_freq=True
```
If the YAML configuration file contains:
```yaml
features_file: NULL # file of features to correlate with ORFs
do_pos_sp_nt_freq: FALSE # Do calculate position-specific nucleotide freqeuency
t_rna: NULL # tRNA estimates
codon_pos: NULL # Codon positions in each gene
```
Running:
```console
$ python -m riboviz.tools.prep_riboviz --dry-run rscripts/ vignette/vignette_config.yaml
```
fails with:
```
Traceback (most recent call last):
  File "/home/ubuntu/RiboViz/riboviz/tools/prep_riboviz.py", line 534, in prep_riboviz
    dry_run)
  File "/home/ubuntu/RiboViz/riboviz/tools/prep_riboviz.py", line 364, in process_sample
    "--t_rna=" + config["t_rna"],
TypeError: can only concatenate str (not "NoneType") to str
```
The problem arises as the configuration value for t_rna is value None in Python.

**Comment by mikej888** [comment]
Created branch check-none-72. 

Commit 2e4e2a2479016c9665a1915689b4608d1b60fa2b checks if any configuration value is `None` in Python (`NULL` in YAML) and, if so, does not add it.

Now if the YAML configuration file contains:

```yaml
features_file: data/yeast_features.tsv # file of features to correlate with ORFs
do_pos_sp_nt_freq: TRUE # Do calculate position-specific nucleotide freqeuency
t_rna: data/yeast_tRNAs.tsv # tRNA estimates
codon_pos: data/yeast_codon_pos_i200.RData # Codon positions in each gene
```
Running:
```console
$ python -m riboviz.tools.prep_riboviz --dry-run rscripts/ vignette/vignette_config.yaml
```
succeeds and prep_riboviz.sh contains:
```
Rscript --vanilla rscripts/generate_stats_figs.R --Ncores=1 --MinReadLen=10 --MaxReadLen=50 --Buffer=250 --PrimaryID=Name --dataset=vignette --hdFile=vignette/output/WT3AT.h5 --out_prefix=vignette/output/WT3AT --orf_fasta=vignette/input/yeast_YAL_CDS_w_250utrs.fa --rpf=True --dir_out=vignette/output --do_pos_sp_nt_freq=True --t_rna=data/yeast_tRNAs.tsv --codon_pos=data/yeast_codon_pos_i200.RData --features_file=data/yeast_features.tsv --orf_gff_file=vignette/input/yeast_YAL_CDS_w_250utrs.gff3
```
If the YAML configuration file contains:
```yaml
features_file: NULL # file of features to correlate with ORFs
do_pos_sp_nt_freq: FALSE # Do calculate position-specific nucleotide freqeuency
t_rna: NULL # tRNA estimates
codon_pos: NULL # Codon positions in each gene
```
Running:
```console
$ python -m riboviz.tools.prep_riboviz --dry-run rscripts/ vignette/vignette_config.yaml
```
also succeeds and prep_riboviz.sh contains:
```
Rscript --vanilla rscripts/generate_stats_figs.R --Ncores=1 --MinReadLen=10 --MaxReadLen=50 --Buffer=250 --PrimaryID=Name --dataset=vignette --hdFile=vignette/output/WT3AT.h5 --out_prefix=vignette/output/WT3AT --orf_fasta=vignette/input/yeast_YAL_CDS_w_250utrs.fa --rpf=True --dir_out=vignette/output --do_pos_sp_nt_freq=False --orf_gff_file=vignette/input/yeast_YAL_CDS_w_250utrs.gff3
```
